### ISSUE TITLE
Promise returned by registerPromise loses the resolved value

### ISSUE THREAD

**Issue by glasser** [hjylewis/trashable-react#1]
This code:

```
      const handledPromise: any = trashablePromise
        .then(() => {
          this.removePromise(key);
        })
        .catch(error => {
          this.removePromise(key);
          return Promise.reject(error);
        });
```

loses track of the successful resolved value in trashablePromise.  That `then` clause is missing a `return val` or `return Promise.resolve(val)`, I think.

**Comment by hjylewis** [comment]
Yes, whoops. That's kind of important isn't 😅 
We should probably have a test for that too...

I'll get around to fixing that soon unless you want to write up a PR.

**Comment by glasser** [comment]
Probably won't have time this week.
