### ISSUE TITLE
Abortable fetch

### ISSUE THREAD

**Issue by Terkhos** [hjylewis/trashable-react#7]
First of all thank you for this, it saved me a lot of time. I have doing some more research on how to also cancel the pending API request and found this paper on abortable fetch, could this be implemented?

https://developers.google.com/web/updates/2017/09/abortable-fetch

Thanks.

**Comment by hjylewis** [comment]
This is very cool. Thanks for sharing!

So, I don't think I'd implement this API into `trashable-react` since this API is for `fetch` specifically and not general promises.

Looks like https://www.npmjs.com/package/use-abortable-fetch might be what you'd want.

**Comment by Terkhos** [comment]
I did not pay attention to that fact and i'm also not using fetch, right now we use axios.

Could there be any options to implement this idea on your plugin? I'm willing to help on this any way i can.

**Comment by hjylewis** [comment]
I can't think of a way to incorporate the `AbortController` api into this library in a way that adds anything.

If you have an idea I'm happy to look at a PR request.

**Comment by hjylewis** [comment]
Does this library not satisfy your needs as is?

**Comment by Terkhos** [comment]
I'm going to take a look into the `AbortController ` and do some research about this (i'm new to React).

The plugin does exactly what i need right now, i just wanted to improve it by not leaving the pending request to my API and try to save some server processing.

**Comment by hjylewis** [comment]
Sounds good.

It's hard to "cancel" an API request once it's made. There's nothing you can really do about it once it's in-flight.

I'm gonna close this issue for now. Feel free to re-open it once you do more research.
